import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "@/Components/Footer/Footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { unstable_setRequestLocale } from "next-intl/server";


const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  
  title: "Portfolio Agustin Maurel",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
  params:{locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
  
}>) {

  const messages = await getMessages()

  unstable_setRequestLocale(locale);
  return (
    <html className='scroll-smooth' lang={locale}>
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body
        className={`flex justify-center items-center bg-black text-white ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>

          
          {children}
          <Footer/>

        </NextIntlClientProvider>
      </body>
    </html>
  );
}
